apiVersion: v1
kind: Service
metadata:
  name: geiaus-web 
  labels:
    run: geiaus-web 
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    run: geiaus-web 
  type: LoadBalancer
